interemediate commit (feature #121)

diff --git a/kbt b/kbt
--- a/kbt
+++ b/kbt
@@ -91,37 +91,85 @@ function do_rsync {
 		music="Music"
 	fi
 
+	local rsync_params=(-vahi --progress $RS_PARAMS --exclude-from=$RSYNC_EXCLUDE_FILE)
+	local rsync_params_delete=("${rsync_params[@]}")
+	rsync_params_delete+=( --delete)
+
 	log_echo "(begin) $msg from $SOURCE to $DEST" >> $FILE_LOG
 	log_echo "(begin) $msg from $SOURCE to $DEST" >> $FILE_ERR_LOG
 
 	if [[ ! -d "$SOURCE/$videos/" ]]; then
 		log_echo "source directory does not exist ($SOURCE/$videos/"
 	else
-		rsync -vahzi --delete --progress $RS_PARAMS "$SOURCE/$videos/" "$DEST/videos/" >> $FILE_LOG 2>> $FILE_ERR_LOG
+		rsync "${rsync_params_delete[@]}" "$SOURCE/$videos/" "$DEST/videos/" >> $FILE_LOG 2>> $FILE_ERR_LOG
 	fi
 	if [[ ! -d "$SOURCE/videos_seen/" ]]; then
 		log_echo "source directory does not exist ($SOURCE/videos_seen/"
 	else
-		rsync -vahzi --progress $RS_PARAMS "$SOURCE/videos_seen/" "$DEST/videos_seen/" >> $FILE_LOG 2>> $FILE_ERR_LOG
+		rsync "${rsync_params[@]}" "$SOURCE/videos_seen/" "$DEST/videos_seen/" >> $FILE_LOG 2>> $FILE_ERR_LOG
 	fi
 	if [[ ! -d "$SOURCE/$music/" ]]; then
 		log_echo "source directory does not exist ($SOURCE/$music/"
 	else
-		rsync -vahzi --delete --progress $RS_PARAMS "$SOURCE/$music/" "$DEST/musics/" >> $FILE_LOG 2>> $FILE_ERR_LOG
+		rsync "${rsync_params_delete[@]}" "$SOURCE/$music/" "$DEST/musics/" >> $FILE_LOG 2>> $FILE_ERR_LOG
 	fi
 	if [[ ! -d "$SOURCE/trainings/" ]]; then
 		log_echo "source directory does not exist ($SOURCE/trainings/"
 	else
-		rsync -vahzi --delete --progress $RS_PARAMS "$SOURCE/trainings/" "$DEST/trainings/" >> $FILE_LOG 2>> $FILE_ERR_LOG
+		rsync "${rsync_params_delete[@]}" "$SOURCE/trainings/" "$DEST/trainings/" >> $FILE_LOG 2>> $FILE_ERR_LOG
 	fi
 	if [[ ! -d "$SOURCE/cloud/" ]]; then
 		log_echo "source directory does not exist ($SOURCE/cloud/"
 	else
-		rsync -vahzi --delete --progress $RS_PARAMS "$SOURCE/cloud/" "$DEST/cloud/" >> $FILE_LOG 2>> $FILE_ERR_LOG
+		rsync "${rsync_params_delete[@]}" "$SOURCE/cloud/" "$DEST/cloud/" >> $FILE_LOG 2>> $FILE_ERR_LOG
 	fi
 
 	log_echo "(end) $msg from $SOURCE to $DEST" >> $FILE_LOG
 	log_echo "(end) $msg from $SOURCE to $DEST" >> $FILE_ERR_LOG
+
+	return 0
+}
+
+function do_rsync_lan {
+	local msg=""
+	if [[ -z $RS_PARAMS ]]; then
+		msg="do lan sync"
+	else
+		msg="do lan sync test"
+	fi
+
+	if [[ ! -f "./$CONFIG" ]]; then
+		log_echo "error: config file: '$CONFIG' does not exist"
+		log_echo " exiting... "
+		exit 1
+	fi
+
+	OLD_IFS=$IFS
+	IFS=$'\n'
+	lines_array=( $(head -n 2 "./$CONFIG") )
+	IFS=$OLD_IFS
+
+	if [[ -z ${lines_array[0]} ]]; then
+		log_echo "error: remote user name and host are not specified"
+		log_echo "use the following format 'user_name@host'"
+		log_echo " exiting... "
+		exit 1
+	fi
+
+	if [[ -z ${lines_array[1]} ]]; then
+		log_echo "remote port is not set, using default port number: 22"
+		lines_array[1]=22
+	fi
+
+	#local rsync_params=(-vahi --progress $RS_PARAMS --exclude-from=$RSYNC_EXCLUDE_FILE --rsh "ssh -p ${lines_array[1]}")
+	local rsync_params=(-vahi --progress $RS_PARAMS --exclude-from=$RSYNC_EXCLUDE_FILE)
+	local rsync_params_delete=("${rsync_params[@]}")
+	rsync_params_delete+=( --delete)
+
+	log_echo "trying to establish connection to '${lines_array[0]}:${lines_array[1]}'..."
+
+	#rsync "${rsync_params_delete[@]}" "$SOURCE/cloud/Dropbox.zip" "${lines_array[0]}:cloud/" >> $FILE_LOG 2>> $FILE_ERR_LOG
+	rsync "${rsync_params_delete[@]}" "$SOURCE/cloud/Dropbox.zip" "/Volumes/kudoji-hdd/hp-mount/cloud/" >> $FILE_LOG 2>> $FILE_ERR_LOG
 
 	return 0
 }
@@ -213,6 +261,8 @@ else
 fi
 
 RS_PARAMS=""
+CONFIG="config.lan"
+RSYNC_EXCLUDE_FILE="exclude.rsync"
 #-----------/constants and variables block
 
 menu_text="Script syncs source and destination folders where
@@ -231,10 +281,12 @@ Please select action:
 2. sync & exit
 3. cleanup dest directory
 4. cleanup source directory
+5. lan sync test & exit
+6. lan sync & exit
 0. exit
 "
 
-menu "$menu_text" 4
+menu "$menu_text" 6
 
 if [[ $menu_return -eq 0 ]]; then
 	echo $MESSAGE_END
@@ -245,6 +297,7 @@ elif [[ $menu_return -eq 1 ]]; then
 	do_rsync
 elif [[ $menu_return -eq 2 ]]; then
 	echo $MESSAGE_START
+	RS_PARAMS=""
 	do_rsync
 	do_cleanup "$DEST"
 	do_drives_sync
@@ -256,6 +309,14 @@ elif [[ $menu_return -eq 4 ]]; then
 	echo $MESSAGE_START
 	do_cleanup "$SOURCE"
 	do_drives_sync
+elif [[ $menu_return -eq 5 ]]; then
+	echo $MESSAGE_START
+	RS_PARAMS="--dry-run"
+	do_rsync_lan
+elif [[ $menu_return -eq 6 ]]; then
+	echo $MESSAGE_START
+	RS_PARAMS=""
+	do_rsync_lan
 fi
 
 echo ""
